# Resources/config/services.yml
services:

    wbw.jquery.datatables.manager:
        class:  WBW\Bundle\JQuery\DataTablesBundle\Manager\DataTablesManager
        arguments: [ "@logger" ]
        public: true
